### PR TITLE
Add a README

### LINKED ISSUE #1: Document how to use this repo
Ideally, in the `README`! Which does not yet exist!

### PR DESCRIPTION
**Pull request by segiddins**
Closes #1

### CODE REVIEW

**Review by greysteil — APPROVED** [review]
Makes sense to me!

**Comment by deivid-rodriguez** [comment]
Before looking at anything else, there's one thing I don't understand. Since this is supposed to be run from the `bundler` repo. Isn't it better that these changes live in the `bundler` repo?

**Comment by deivid-rodriguez** [comment]
I think I understood the idea now, thanks @segiddins! So... the CSV files are maintained manually (with the aid of the `open_prs_since` script), and from them you generate the final change log (with the `changes` script), that you then copy to bundler?

I guess the most interesting review here is @colby-swandale's, since he has been doing the latest releases.

**Comment by segiddins** [comment]
> Before looking at anything else, there's one thing I don't understand. Since this is supposed to be run from the bundler repo. Isn't it better that these changes live in the bundler repo?

It's in a separate repo so changes can be made that don't need to then be logged in the list of changes ;)

**Review by colby-swandale — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
> It's in a separate repo so changes can be made that don't need to then be logged in the list of changes ;)

mmmm... May I ask why we you don't want to log changes to these scripts? Is doing it likely to cause any problems?

**Comment by segiddins** [comment]
Because if you had to make a PR to update the changelog in bundler, you'd have to log that PR in the list of changes!

**Comment by deivid-rodriguez** [comment]
But you can still make changes in the changelog without going through a PR. I mean, isn't that what's currently done? I always see a "Version 1.x.y with changelog" that's pushed directly to the stable branch without going through a PR? Oh god, this Russell's Paradox stuff is tough :)

I'm also wondering if this is necessary, since this repo hasn't been updated for 3 releases now? I think I rememeber that @colby-swandale was actually using it, but he just didn't push the changes?

**Comment by segiddins** [comment]
I used it when releasing the 1.16 pres, 1.16.0, and 1.16.1

**Comment by deivid-rodriguez** [comment]
I didn't use this repo in the end for releasing bundler, so I guess we should close this PR and archive this repo? It hasn't been used since bundler 1.16.1.

**Comment by indirect** [comment]
Sounds good to me.

**Pull request closed without merging**
